application: tabletop-tryouts
version: alpha-001
runtime: go
api_version: go1

handlers:
- url: /
  script: login
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /assets
  static_dir: static/assets

- url: /(login|signup|logout)
  script: login
